print("Hello user this is the MLG project!")
print("Genre Options: Adventure, Anime, Futuristic, or Action (Case Sensitve)")
whatGenre = input("What genre would you like to play: ")
if whatGenre == "Adventure":
    adjective1 = input("Enter a(n) adjective: ")
    noun1 = input("Enter a(n) noun: ")
    noun2 = input("Enter a(n) noun: ")
    noun3 = input("Enter a(n) noun: ")
    adjective2 = input("Enter a(n) adjective: ")
    noun4 = input("Enter a(n) noun: ")
    noun5 = input("Enter a(n) noun: ")
    adjective3 = input("Enter a(n) adjective: ")
    pastTenseVerb1 = input("Enter a(n) past tense verb: ")
    noun6 = input("Enter a(n) noun: ")
    noun7 = input("Enter a(n) noun: ")
    pastTenseVerb2 = input("Enter a(n) past tense verb: ")
    pastTenseVerb3 = input("Enter a(n) past tense verb: ")
    noun8 = input("Enter a(n) noun: ")
    noun9 = input("Enter a(n) noun: ")
    verb1 = input("Enter a(n) verb: ")
    verb2 = input("Enter a(n) verb: ")
    verb3 = input("Enter a(n) verb: ")
    adjective4 = input("Enter a(n) adjective: ")
    adjective5 = input("Enter a(n) adjective: ")
    adjective6 = input("Enter a(n) adjective: ")
    print ("It was a " + adjective1 + " summer day. ")
    print(noun1 + " and I was excited to go camping at " + noun2 + ".")
    print("It was my first time going there.")
    print("I packed my favorite " + noun3 + ".")
    print("It is "+ adjective2 + " and " + adjective3 + " perfect for camping!")
    print("On the road we went in our " + adjective4 + " van!")
    print("We were listening to " + noun4 + " all the way down.")
    print("The drive was about 5 hours but it was so worth it.")
    print("When we got there we unpacked the van.")
    print("I could smell " + noun5 + " being cooked.")
    print("It smelled " + adjective5 + ".")
    print("I " + pastTenseVerb1 + " to the room I was staying with my " + noun6 + ".")
    print("The next thing I knew, " + noun6 + " came and " + pastTenseVerb2 + " on the bed.")
    print("I heard my mom scream,"" Get off the bed!""")
    print("I " + pastTenseVerb3 + " outside.")
    print("I saw " + noun7 + ".")
    print("Over the next few days I got to " + verb1 + ".")
    print("My camping trip was " + adjective6)

elif whatGenre == "Anime":
    animeVerb1 = input("Enter a(n) verb: ")
    animeNoun1 = input("Enter a(n) noun: ")
    animeNoun2 = input("Enter a(n) noun: ")
    animeNoun3 = input("Enter a(n) noun: ")
    animePastTenseVerb1 = input("Enter a(n) past tense verb: ")
    animePastTenseVerb2 = input("Enter a(n) past tense verb: ")
    animeNoun4 = input("Enter a(n) noun: ")
    animeAdjective1 = input("Enter a(n) adjective: ")
    animeVerb4 = input("Enter a(n) verb: ")
    animeNoun5 = input("Enter a(n) noun: ")
    animeVerb5 = input("Enter a(n) verb: ")
    print("Sasuke: I'm the only one who could " + animeVerb1 + " that " + animeNoun1)
    print("Sakura: What? Who? You mean the " + animeNoun2)
    print(" ")
    print("Sasuke: That " + animeNoun3 + " I was " + animePastTenseVerb1)
    print(" ")
    print("Sakura: When were you " + animePastTenseVerb2)
    print("Sasuke: It was my " + animeNoun4)
    print(" ")
    print("Sakura: What happened to you?")
    print("Sasuke: I am an avenger that means I must be " + animeAdjective1 + " than my prey")
    print("I need this training there is no time for setbacks")
    print(" ")
    print("Sakura: *flashback*")
    print("     <<Sasuke: Im going to restore my clan and destroy a certain " + animeNoun5 + ">>")
    print(" ")
    print("Sasuke: Ugh. I " + animeVerb5 + " too much time")
    print("Sakura: Sasuke...")

elif whatGenre == "Futuristic":
    futuristicNoun1 = input("Enter a(n) noun: ")
    futuristicPluralNoun1 = input("Enter a(n) plural noun: ")
    futuristicVerb1 = input("Enter a(n) verb: ")
    futuristicVerb2 = input("Enter a(n) verb: ")
    futuristicNoun2 = input("Enter a(n) noun: ")
    futuristicAdjective1 = input("Enter a(n) adjective: ")
    futuristicPluralNoun2 = input("Enter a(n) plural noun: ")
    futuristicAdjective2 = input("Enter a(n) adjective: ")
    print("           THE MAGIC COMPUTER")
    print("Today, every student has a computer small enough to")
    print("fit into his " + futuristicNoun1+". He can solve any problem")
    print("by simply pushing the computers little " + futuristicPluralNoun1+".")
    print("Computers can walk, talk, and " + futuristicVerb1 +".")
    print("They can also " + futuristicVerb2 + " better than a human!")
    print("Some computers are " + futuristicNoun2 + ".")
    print("Others have a(n) " + futuristicAdjective1 + " screen that shows")
    print("all kinds of " + futuristicPluralNoun2 + " and " + futuristicAdjective2 + " figures.")

elif whatGenre == "Action":
    actionName1 = input("Enter a(n) name: ")
    actionNoun1 = input("Enter a(n) noun: ")
    actionName2 = input("Enter a(n) name: ")
    actionVerb1 = input("Enter a(n) verb: ")
    actionName3 = input("Enter a(n) name: ")
    actionNoun2 = input("Enter a(n) noun: ")
    actionCity = input("Enter a(n) city: ")
    actionVerb2 = input("Enter a(n) verb: ")
    actionVerb3 = input("Enter a(n) verb: ")
    actionVerb4 = input("Enter a(n) verb: ")
    actionNoun3 = input("Enter a(n) noun: ")
    actionNoun4 = input("Enter a(n) noun: ")
    print("Hi! My name is " + actionName1 + " and I have a secret to share.")
    print("I'm a normal person by day, and a " + actionNoun1 + " by night.")
    print("Only you and my best friend " + actionName2 + " know my secret.")
    print("At night I " + actionVerb1 + " with " + actionName3 + "!")
    print("Then I bring him/her to a " + actionNoun2 + ".")
    print("My mission is to always save the people of " + actionCity + ".")
    print("One time I had to " + actionVerb2 + " with a lion!")
    print("Another time I had to " + actionVerb3 + " with a electric eel!")
    print("And right now im " + actionVerb4 + " with superman!")
    print("Anyway my life is like a " + actionNoun3 + ".")
    print("I have my bad moments to! Like how someone turned me into a " + actionNoun4)
    print("Not so exciting is it now.")


